# Generated by Django 4.2 on 2023-04-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashop_app', '0003_alter_pizza_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='pizzashop_app/photo', verbose_name='Фото'),
        ),
    ]
